# Generated by Django 3.2.4 on 2021-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210922_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('QR Scanner', 'QR Scanner'), ('E-sewa', 'E-sewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
