# Generated by Django 3.2.4 on 2021-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20210926_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('QR Scanner', 'QR Scanner'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
